config/routes.rb
Rails.application.routes.draw do
    devise_for :users
    root 'rooms#index'
    resources :rooms, only: [:create, :show, :destroy] do
        resources :members, only: [:create, :update, :destroy]
    end
    get '/members/count', to: 'members#member_count'
    get 'change_locale/:locale', to: 'application#change_locale', as: 'change_locale'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/member.rb
class Member < ApplicationRecord
    belongs_to :room

    validates :name, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
    belongs_to :user
    has_many :members

    validates :room_name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
    devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable

    has_many :rooms

    validates :nickname, presence: true

    VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i
    validates :password, format: { with: VALID_PASSWORD_REGEX }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_locale
    before_action :authenticate_user!
    before_action :configure_permitted_parameters, if: :devise_controller?

    def set_locale
        I18n.locale = session[:locale] || I18n.default_locale
    end

    def change_locale
        session[:locale] = params[:locale]
        redirect_back(fallback_location: root_path)
    end

    private

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
    end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
    def create
        room = Room.find(params[:room_id])
        @member = room.members.build(member_params)
        if @member.save
            redirect_to room_path(room.id)
        end
    end

    def update
        room = Room.find(params[:room_id])
        @member = Member.find(params[:id])
        @member.update(member_params)
        redirect_to room_path(room.id)
    end

    def destroy
        room = Room.find(params[:room_id])
        @member = Member.find(params[:id])
        @member.destroy
        redirect_to room_path(room.id)
    end

    def member_count
        member_count = Member.count
        render json: { member_count: member_count }
    end

    private

    def member_params
        params.permit(:name, :fraction)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
    def index
        user = current_user
        @rooms = user.rooms
    end

    def create
        @room = Room.new(room_params)
        if @room.save
            redirect_to root_path
        end
    end

    def show
        @room = Room.find(params[:id])
        @members = @room.members
    end

    def destroy
        room = Room.find(params[:id])
        room.destroy
        redirect_to root_path
    end

    private

    def room_params
        params.permit(:room_name).merge(user_id: current_user.id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WarikanApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Crimson+Text&family=M+PLUS+Rounded+1c:wght@300&family=Noto+Sans+JP:wght@300&family=Oswald:wght@600&family=Rampart+One&family=Roboto:wght@100&family=Space+Grotesk:wght@700&family=Teko:wght@600&family=Work+Sans:ital,wght@0,500;1,700&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rooms/index.html.erb
<%= render "shared/header" %>

<main>
    <div class="container">
        <div class="main-top">
            <p class="nickname"><%= current_user.nickname %></p>
        </div>

        <div class="room-create-area">
            <%= link_to I18n.t('Room create'), "#", class: "room-create-link", id: "open_modal" %>
        </div>

        <%= render "shared/modal" %>

        <div class="room-area">
            <p class="room-area-text"><%= "＜ #{I18n.t('Rooms')} ＞" %></p>
            <% @rooms.each do |room| %>
            <ul class="room-lists">
                <li class="room-flex">
                    <%= link_to room.room_name, room_path(room.id), class: "room" %>
                    <%= link_to I18n.t('delete'), room_path(room.id), data: { turbo_method: :delete }, class: "room-delete-btn" %>
                </li>
            </ul>
            <% end %>
        </div>
    </div>
</main>

app/views/rooms/show.html.erb
<%= render "shared/second-header" %>

<div class="show-container">
    <div class="room-top">
        <p class="room-name"><%= @room.room_name %></p>
        <%= link_to "<<#{I18n.t('back')}", root_path, class: "back-btn" %>
    </div>

    <div class="member-area">
        <div class="member-area-top">
            <p class="member-area-text"><%= "＜ #{I18n.t('Member List')} ＞" %></p>
        </div>

        <div class="member-main">
            <ul class="member-lists">
            <% @members.each do |member| %>
                <li class="member">
                    <p class="member-name"><%= member.name %></p>
                    <div class="member-result">
                        <p class="member-money">¥ </p>
                        <%= form_with(model: @member, url: room_member_path(@room, member), method: :patch) do |f| %>
                            <span class="member-fraction"><%= I18n.t('fraction') %>
                                <%= f.number_field :fraction, class: "fraction-input", data: { name: member.name }, value: member.fraction, readonly: true %>
                            </span>
                            <%= f.submit I18n.t('Decision'), class: "update-fraction-button" %>
                        <% end %>
                    </div>
                    <%= link_to I18n.t('delete'), room_member_path(@room, member), data: { turbo_method: :delete }, class: "member-delete-btn" %>
                </li>
            <% end %>
            </ul>
        </div>

        <div class="member-create-area">
            <%= link_to I18n.t('Member create'), "#", class: "member-create-link", id: "open_second_modal", data: { member_count: @members.count } %>
        </div>

        <%= render "shared/second-modal" %>

    </div>

    <div class="show-main">
        <div class="calculator-area">
            <input type="text" class="display" readonly>
            <div class="buttons">
                <button class="btn-C button">C</button>
                <button class="btn button">/</button>
                <button class="btn button">7</button>
                <button class="btn button">8</button>
                <button class="btn button">9</button>
                <button class="btn button">*</button>
                <button class="btn button">4</button>
                <button class="btn button">5</button>
                <button class="btn button">6</button>
                <button class="btn button">-</button>
                <button class="btn button">1</button>
                <button class="btn button">2</button>
                <button class="btn button">3</button>
                <button class="btn button">+</button>
                <button class="btn button">0</button>
                <button class="btn button">00</button>
                <button class="btn button">.</button>
                <button class="btn button">=</button>
            </div>
        </div>

        <div class="warikan-area">
            <div class="share-area">
                <div class="share-inputs">
                    <span class="share-text"><%= I18n.t('total') %></span><input type="number" class="share-input" id="total">
                    <button class= "fair-share", id= "fair_share">Fair Share</button>
                    <button class= "clear", id= "clear">Clear</button>
                </div>
                <span class="share-text"><%= I18n.t('per person') %></span><input type="number" class="share-input" id="per_person" readonly>
                <span class="share-text"><%= I18n.t('fraction') %></span><input type="number" class="share-input" id="fraction_input" readonly>
            </div>

            <div class="pay-select-area">
                <div class="select-text-area">
                    <p class="select-text"><%= "＜ #{I18n.t('Pay The Fraction')} ＞" %></p>
                </div>
                <div class="pay-select">
                    <div class="select-member-area">
                        <% @members.each do |member| %>
                        <button class="select-member" data-member-name="<%= member.name %>"><%= member.name %></button>
                        <% end %>
                    </div>
                    <div class="random-area">
                        <p class="random-text">＜ Random Select ＞</p>
                        <div id="random-display"></div>
                        <div class="random-btn">
                            <button id="random">Random</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/shared/_devise-header.html.erb
<header>
    <div class="header-texts">
        <h1 class="header-title">Fair Share</h1>
    </div>
</header>

app/views/shared/_header.html.erb
<header>
    <div class="header-left">
        <h1 class="header-title">Fair Share</span></h1>
    </div>
    <div class="header-right">
        <%= link_to I18n.t('Logout'), destroy_user_session_path, data: { turbo_method: :delete }, class: "log-out" %>
        <%= link_to "English", change_locale_path(locale: :en), class: "en" %> |
        <%= link_to "日本語", change_locale_path(locale: :ja), class:"ja" %>
    </div>
</header>

app/views/shared/_modal.html.erb
<div class="modal" id="confirmationModal">
    <div class="room-create-modal">
        <%= form_with model: @room, url: rooms_path, class: "room-create-form", local: true do |f| %>
            <div class="modal-top">
                <p class="modal-top-text">＜ Room Name ＞</p>
            </div>
            <div class="modal-form">
                <%= f.text_area :room_name, class:"room-name-form", maxlength:"40" %>
            </div>
            <div class="modal-bottom">
                <%= f.submit "Create" ,class:"room-create-btn" %>
            </div>
        <% end %>
    </div>
</div>

app/views/shared/_second-header.html.erb
<header>
    <div class="header-texts">
        <h1 class="header-title">Fair Share</h1>
        <div class="language">
            <%= link_to "English", change_locale_path(locale: :en), class: "en" %> |
            <%= link_to "日本語", change_locale_path(locale: :ja), class: "ja" %>
        </div>
    </div>
</header>

app/views/shared/_second-modal.html.erb
<div class="modal" id="confirmationSecondModal">
    <div class="room-create-modal">
        <%= form_with model: @member, url: room_members_path(@room), class: "room-create-form", local: true do |f| %>
            <div class="modal-top">
                <p class="modal-top-text">＜ Member Name ＞</p>
            </div>
            <div class="modal-form">
                <%= f.text_area :name, class:"room-name-form", maxlength:"40" %>
            </div>
            <div class="modal-bottom">
                <%= f.submit "Create" ,class:"room-create-btn" %>
            </div>
        <% end %>
    </div>
</div>